# This file was generated by GoReleaser. DO NOT EDIT.
cask "rxtls" do
  desc "High-Performance Certificate Transparency Processor"
  homepage "https://github.com/x-stp/rxtls"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rxtls"

  on_macos do
    on_intel do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.2/rxtls_0.2.2_macOS_amd64.tar.gz"
      sha256 "a84d3f9fc7f0b8cb784a3c643a4b38d6e1edee6e25ef853ce8fae8e5079dcc57"
    end
    on_arm do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.2/rxtls_0.2.2_macOS_arm64.tar.gz"
      sha256 "3fe0954089747cc8f2c4fa6e2ffa2dc590f7d166e06e2eb41db6eacb82f6057d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.2/rxtls_0.2.2_linux_amd64.tar.gz"
      sha256 "8c3c2c8d63b7b58b1c170dadb1e1fd57ea595a1ba26b35379cae465b59cb6466"
    end
    on_arm do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.2/rxtls_0.2.2_linux_arm64.tar.gz"
      sha256 "0ce50ca57b327892b4d12fd0d53f5564fb37bf130c49868ec8ace472fe10e369"
    end
  end

  conflicts_with formula: [
      "rxtls",
    ]

  # No zap stanza required
end
