# This file was generated by GoReleaser. DO NOT EDIT.
cask "rxtls" do
  desc "High-Performance Certificate Transparency Processor"
  homepage "https://github.com/x-stp/rxtls"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rxtls"

  on_macos do
    on_intel do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.1/rxtls_0.2.1_macOS_amd64.tar.gz"
      sha256 "0668798d3752be6c3a7b6af2e6e81a7d0e48f819b0fd384d5ea3a7489dd3e0dd"
    end
    on_arm do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.1/rxtls_0.2.1_macOS_arm64.tar.gz"
      sha256 "0ef3303c71d8c4778a8b1920da4e91a92d67f8dcb759f2be140380b25cde58b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.1/rxtls_0.2.1_linux_amd64.tar.gz"
      sha256 "3a2f357672552289f4e45c0feeb77534a532fb5f19f0e8e7e290e6869b6c41bb"
    end
    on_arm do
      url "https://github.com/x-stp/rxtls/releases/download/v0.2.1/rxtls_0.2.1_linux_arm64.tar.gz"
      sha256 "8b113a85b2bbbb84f782ceb7c70b20c6cbf1954dede2a0b1eabca880cf799aa9"
    end
  end

  conflicts_with formula: [
      "rxtls",
    ]

  # No zap stanza required
end
